# Generated by Django 5.0.5 on 2024-05-07 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='joined_date',
            field=models.DateTimeField(verbose_name='date joined'),
        ),
    ]
