# Generated by Django 5.0.5 on 2024-05-07 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_teacher_joined_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='joined_date',
            field=models.DateField(verbose_name='date joined'),
        ),
    ]
