# Generated by Django 5.0.5 on 2024-05-07 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_notice'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='student',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='notice',
            name='teacher',
            field=models.BooleanField(default=True),
        ),
    ]
