# Generated by Django 5.0.5 on 2024-05-07 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_notice_student_notice_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='faculty',
            field=models.ManyToManyField(to='base.faculty'),
        ),
    ]
