# Generated by Django 5.0.5 on 2024-05-08 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_student_roll_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='password',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='password_2',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='username',
            field=models.CharField(default='<django.db.models.fields.CharField><django.db.models.fields.CharField>', max_length=50),
        ),
        migrations.AddField(
            model_name='teacher',
            name='password',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='teacher',
            name='password_2',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='teacher',
            name='username',
            field=models.CharField(default='<django.db.models.fields.CharField><django.db.models.fields.CharField>', max_length=50),
        ),
    ]
