# Generated by Django 5.0.5 on 2024-05-08 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_student_password_alter_student_password_2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='roll_no',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='joined_date',
        ),
    ]
