# Generated by Django 5.0.5 on 2024-05-08 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_remove_student_roll_no_remove_teacher_joined_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='password_2',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='password_2',
        ),
    ]
