# Generated by Django 5.0.5 on 2024-05-08 06:51

import base.models
import django_enumfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_student_id_type_teacher_id_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='id_type',
            field=django_enumfield.db.fields.EnumField(default=2, enum=base.models.TypeEnum),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='id_type',
            field=django_enumfield.db.fields.EnumField(default=1, enum=base.models.TypeEnum),
        ),
    ]
