# Generated by Django 5.0.5 on 2024-05-08 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_alter_student_id_type_alter_teacher_id_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='birth_date',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='teacher',
            name='birth_date',
            field=models.DateField(default=None),
        ),
    ]
