# Generated by Django 5.0.5 on 2024-05-08 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_alter_student_faculty_alter_teacher_faculty'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='pub_date',
            field=models.DateField(default=None),
        ),
    ]
