# Generated by Django 5.0.5 on 2024-05-08 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_alter_notice_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='pub_date',
            field=models.DateTimeField(verbose_name='date published'),
        ),
    ]
