# Generated by Django 5.0.6 on 2024-05-20 10:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_todo_url_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='url_id',
            field=models.UUIDField(default=uuid.UUID('db82fa4a-58a9-408a-bdd6-2fd8e15e7138'), editable=False, primary_key=True, serialize=False),
        ),
    ]
