# Generated by Django 5.0.6 on 2024-05-15 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalinformation',
            name='descibe',
        ),
        migrations.AddField(
            model_name='personalinformation',
            name='summary',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='github',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='linkedin',
            field=models.URLField(null=True),
        ),
    ]
