# Generated by Django 5.0.6 on 2024-05-13 14:05

import base.enums
import django_enumfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=django_enumfield.db.fields.EnumField(default='Others', enum=base.enums.Gender_choice),
        ),
    ]
