# Generated by Django 5.0.6 on 2024-05-13 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_customuser_user_customuser_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(default='<django.db.models.fields.CharField>+<django.db.models.fields.CharField>', max_length=50),
        ),
    ]
