# Generated by Django 5.0.6 on 2024-05-13 14:27

import base.enums
import django_enumfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_customuser_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=django_enumfield.db.fields.EnumField(default=3, enum=base.enums.Gender_choice),
        ),
    ]
