# Generated by Django 5.0.6 on 2024-05-15 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_personalinformation_descibe_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='enddate',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='startdate',
            new_name='start_date',
        ),
    ]
