# Generated by Django 5.0.6 on 2024-06-10 05:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.basemodel')),
            ],
            bases=('base.basemodel',),
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.basemodel')),
            ],
            bases=('base.basemodel',),
        ),
        migrations.CreateModel(
            name='Muncipality',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.basemodel')),
                ('district_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='muncipality', to='base.district')),
            ],
            bases=('base.basemodel',),
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.basemodel')),
                ('country_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='province', to='base.country')),
            ],
            bases=('base.basemodel',),
        ),
        migrations.AddField(
            model_name='district',
            name='province_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='district', to='base.province'),
        ),
    ]
