# Generated by Django 5.0.6 on 2024-06-10 05:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='muncipality',
            name='country_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='muncipality', to='base.country'),
        ),
        migrations.AddField(
            model_name='muncipality',
            name='province_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='muncipality', to='base.province'),
        ),
        migrations.AlterField(
            model_name='muncipality',
            name='district_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='muncipality', to='base.district'),
        ),
    ]
