# Generated by Django 5.0.6 on 2024-06-10 06:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_muncipality_country_id_muncipality_province_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='district',
            name='province_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='district', to='base.province'),
        ),
        migrations.AlterField(
            model_name='province',
            name='country_id',
            field=models.ForeignKey(default='Nepal', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='province', to='base.country'),
        ),
    ]
