# Generated by Django 5.0.6 on 2024-06-10 06:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_district_province_id_alter_province_country_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='province',
            name='country_id',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='province', to='base.country'),
        ),
    ]
