# Generated by Django 5.0.6 on 2024-06-10 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_province_country_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basemodel',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
