# Generated by Django 5.0.6 on 2024-06-10 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_basemodel_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='muncipality',
            name='country_id',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='muncipality', to='base.country'),
        ),
    ]
