# Generated by Django 5.0.6 on 2024-06-01 15:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_ticket_recent_user_alter_ticket_solved_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='recent_user',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='token_editor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='solved_by',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='token_solver', to=settings.AUTH_USER_MODEL),
        ),
    ]
