# Generated by Django 5.0.6 on 2024-06-03 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='bug_type',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
