# Generated by Django 5.0.6 on 2024-06-03 10:04

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_ticket_bug_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='bug_type',
            field=models.CharField(blank=True, default='', max_length=50, validators=[base.models.bug_validation]),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Forwarded', 'Forwarded'), ('Resolved', 'Resolved'), ('Decline', 'Decline')], default='Pending', max_length=20),
        ),
    ]
