# Generated by Django 5.0.6 on 2024-06-03 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_ticket_bug_type_alter_ticket_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='profile_picture',
        ),
    ]
